spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1013
  profiles:
    active: production
jwt:
  secret: portfolio.blog.key