spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel5.cloudtype.app:30333/blog_231026
    username: root
    password: root