spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel5.cloudtype.app:32723/blog
    username: root
    password: root
jwt:
  secret: portfolio.blog.key
logging.level.org.springframework: DEBUG