name: userImg

on: [push]

env:
  USER_IMAGE_NAME: hkim7095/blog_user

jobs:
  build-and-push-user-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.USER_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker user image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.USER_IMAGE_NAME }}:tagname

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: blog-portfolio/blog
          stage: main
          yaml: |
            name: blog
            type: container
            options:
              ports: 8080
              image: ${{ steps.meta.outputs.tags }}
